### ISSUE TITLE
iOS Safari bug on demo page

### ISSUE THREAD

**Issue by andrey-hohlov** [callmecavs/bricks.js#30] opened 2016-08-29 03:04 UTC
Latest Safari, iPad
![image](https://cloud.githubusercontent.com/assets/7358151/18039750/e829e9fc-6dcf-11e6-9009-d9aadac4b79b.png)

**Comment by callmecavs** [comment] 2016-08-31 00:46
thanks for the heads up man. closing because it's caused by #25

**Closed as completed by callmecavs** 2016-08-31 00:46 UTC

**Comment by callmecavs** [comment] 2017-03-22 21:52
@andrey-hohlov fixed in the latest [release](https://github.com/callmecavs/bricks.js/releases/tag/v1.8.0), apologies for the delay
