### ISSUE TITLE
`display:none` on a grid item breaks everything

### ISSUE THREAD

**Issue by josephrocca** [callmecavs/bricks.js#25] opened 2016-06-15 18:39 UTC
Minimal example: https://jsfiddle.net/1s5o685n/
If you remove the `display:none;` inline style from the first grid item in the above example, it works fine.

I'd like to be able to filter my grid items by hiding some and then re-packing them. Is there a way to do this? Seems like items with `display:none` should be ignored in the packing process.

Cheers

**Comment by josephrocca** [comment] 2016-06-28 11:19
@callmecavs sorry to ping you directly on this, but could you confirm whether this will be fixed any time soon? Just want to know whether I should move on or wait a bit. Cheers

**Comment by callmecavs** [comment] 2016-06-28 13:49
@josephrocca happy to look at a PR if you open one - not sure when I'll get around to fixing this to be honest.

**Comment by blakerutledge** [comment] 2016-06-28 14:19
@josephrocca a while back (i think callmecavs has updated bricks since) i modified bricks a bit to work for my own use case, but its very similar to the one you are describing i think. I dont have the source with me but can share it this evening. I forget exactly how i did it, but it wasn't anything crazy. For now you can see it [working here](http://geofflevy.com/) click the art direction, commercial etc filters to see it sort and repack ... Next up is figuring how to best pack the grid and lazy load the images...

**Comment by josephrocca** [comment] 2016-07-02 17:54
Thanks people! I think I'll have to give it a miss as my project doesn't give me much room for cracking open other libraries. @callmecavs it might be worth putting a warning in the readme because I think otherwise people would assume it supports hiding elements, and lose a bit of time trying to work it out like I did.

**Comment by callmecavs** [comment] 2016-07-05 05:12
@josephrocca fixed this. my apologies for the delay. upgrade to [v1.5.0](https://github.com/callmecavs/bricks.js/releases/tag/v1.5.0) and your hidden elements wont be a problem

@blakerutledge is a local legend, and quite a talented developer (which I can say confidently, having worked with him before). he used this library before I ever thought about open sourcing it, and that site he linked is perhaps the most advanced usage of it in the wild. another release coming soon that will support positioning elements with transforms, to allow animated changes to the grid. kudos to him for modifying the source to produce that effect without my input.

**Comment by josephrocca** [comment] 2016-07-12 03:08
@callmecavs @blakerutledge Sorry for the late reply. Thanks a tonne for the work you've both done with this, and thanks callmecavs for the latest updates!
Hopefully just some teething problems, but I tried 1.5.0 and 1.7.0 and am getting weird behaviour:

https://jsfiddle.net/1s5o685n/1/    (this is using 1.7.0)

If you remove `display:none;` from the first grid item, it works fine.

**Comment by callmecavs** [comment] 2016-07-12 04:50
@josephrocca reopening this - the problem is in the [`setNodesDimensions`](https://github.com/callmecavs/bricks.js/blob/master/src/bricks.js#L115-L122) function. it relies exclusively on the first node (the one you've set to `display: none`) to calculate the width of the others. Should be a quick fix, I'll take care of it this week. Good catch.

**Comment by blakerutledge** [comment] 2016-07-12 05:15
@josephrocca  @callmecavs Oh thats right... i remember having to fix this function. Now it just tries until it gets an element's width that is non-zero. now that i look again, it should probably also handle the case that every object is hidden.

```
  function setElementDimensions() {
    let index = 0
    width = 0
    while(width === 0) {
      width = elements[index].clientWidth
      index++
    }
    heights = elements.map(element => element.clientHeight)
  }
```

**Comment by callmecavs** [comment] 2016-07-12 05:19
@blakerutledge yep, I remember us cooking that up haha. the problem with that fix is that it breaks if a node has a width but no height.

**Comment by josephrocca** [comment] 2016-08-22 13:37
@callmecavs Any progress on this one? :)

**Comment by callmecavs** [comment] 2016-08-23 18:32
@josephrocca negative - very busy as of late. will be sure to let people know when it's fixed. for now, I'd recommend using an older version.

**Comment by josephrocca** [comment] 2016-08-26 13:23
No worries - looking forward to being able to use it, older versions don't
work because I want to be able to hide some elements (the reason I reported
this issue in the first place). Cheers

**Comment by blakerutledge** [comment] 2016-10-20 18:43
😭😞👏🏼

**Comment by appinteractive** [comment] 2017-03-13 11:11
To be honest I would expect it to be broken on display:none element as the have no dimension. This is a known "issue" in CSS as that element is no rendered. Can't you just use visibility:hidden on the item?

**Comment by callmecavs** [comment] 2017-03-22 21:55
@josephrocca @blakerutledge @josephrocca @appinteractive this should be fixed in the latest [release](https://github.com/callmecavs/bricks.js/releases/tag/v1.8.0), apologies for the delay

**Closed as completed by callmecavs** 2017-03-22 21:55 UTC
Labels: bug
